// frontend/seller-dashboard/src/pages/CatalogPage.tsx
import { FormEvent, useEffect, useState } from "react";
import { sellerApi, type Product } from "../api";

export function CatalogPage() {
  const [products, setProducts] = useState<Product[]>([]);
  const [error, setError] = useState("");
  const [title, setTitle] = useState("");
  const [price, setPrice] = useState("");
  const [currency, setCurrency] = useState("RUB");
  const [keywords, setKeywords] = useState("");

  async function load() {
    const data = await sellerApi.products();
    setProducts(data.products);
  }

  useEffect(() => {
    load().catch((e) => setError(e.message));
  }, []);

  async function onCreate(e: FormEvent) {
    e.preventDefault();
    setError("");
    try {
      await sellerApi.createProduct({
        title,
        price,
        currency,
        keywords: keywords
          .split(",")
          .map((k) => k.trim())
          .filter(Boolean),
        is_active: true,
      });
      setTitle("");
      setPrice("");
      setKeywords("");
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Ошибка");
    }
  }

  async function toggle(product: Product) {
    await sellerApi.updateProduct(product.id, {
      title: product.title,
      price: product.price,
      currency: product.currency,
      keywords: product.keywords,
      is_active: !product.is_active,
    });
    await load();
  }

  async function remove(id: number) {
    await sellerApi.deleteProduct(id);
    await load();
  }

  return (
    <div>
      <h2>Каталог</h2>
      {error && <p className="error">{error}</p>}

      <div className="card">
        <h3>Добавить товар</h3>
        <form onSubmit={onCreate}>
          <input placeholder="Название" value={title} onChange={(e) => setTitle(e.target.value)} required />
          <input placeholder="Цена" value={price} onChange={(e) => setPrice(e.target.value)} required />
          <input placeholder="Валюта" value={currency} onChange={(e) => setCurrency(e.target.value)} />
          <input
            placeholder="Keywords через запятую"
            value={keywords}
            onChange={(e) => setKeywords(e.target.value)}
          />
          <button type="submit">Добавить</button>
        </form>
      </div>

      <div className="card">
        <table>
          <thead>
            <tr>
              <th>Товар</th>
              <th>Цена</th>
              <th>Keywords</th>
              <th>Статус</th>
              <th />
            </tr>
          </thead>
          <tbody>
            {products.map((p) => (
              <tr key={p.id}>
                <td>{p.title}</td>
                <td>
                  {p.price} {p.currency}
                </td>
                <td>{p.keywords.join(", ") || "—"}</td>
                <td>{p.is_active ? "активен" : "выкл"}</td>
                <td className="row">
                  <button className="secondary" onClick={() => void toggle(p)}>
                    {p.is_active ? "Выключить" : "Включить"}
                  </button>
                  <button className="danger" onClick={() => void remove(p.id)}>
                    Удалить
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// services/web/apps/seller-dashboard/src/pages/CatalogPage.vue
<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import { sellerApi, type Product } from "../api";

const products = ref<Product[]>([]);
const error = ref("");
const title = ref("");
const price = ref("");
const currency = ref("RUB");
const keywords = ref("");

async function load() {
  const data = await sellerApi.products();
  products.value = data.products;
}

onMounted(() => {
  load().catch((e) => {
    error.value = e instanceof Error ? e.message : "Ошибка загрузки";
  });
});

async function onCreate() {
  error.value = "";
  try {
    await sellerApi.createProduct({
      title: title.value,
      price: price.value,
      currency: currency.value,
      keywords: keywords.value
        .split(",")
        .map((k) => k.trim())
        .filter(Boolean),
      is_active: true,
    });
    title.value = "";
    price.value = "";
    keywords.value = "";
    await load();
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Ошибка";
  }
}

async function toggle(product: Product) {
  await sellerApi.updateProduct(product.id, {
    title: product.title,
    price: product.price,
    currency: product.currency,
    keywords: product.keywords,
    is_active: !product.is_active,
  });
  await load();
}

async function remove(id: number) {
  await sellerApi.deleteProduct(id);
  await load();
}
</script>

<template>
  <div>
    <h2>Каталог</h2>
    <p v-if="error" class="error">{{ error }}</p>

    <div class="card">
      <h3>Добавить товар</h3>
      <form @submit.prevent="onCreate">
        <input v-model="title" placeholder="Название" required />
        <input v-model="price" placeholder="Цена" required />
        <input v-model="currency" placeholder="Валюта" />
        <input v-model="keywords" placeholder="Keywords через запятую" />
        <button type="submit">Добавить</button>
      </form>
    </div>

    <div class="card">
      <table>
        <thead>
          <tr>
            <th>Товар</th>
            <th>Цена</th>
            <th>Keywords</th>
            <th>Статус</th>
            <th />
          </tr>
        </thead>
        <tbody>
          <tr v-for="p in products" :key="p.id">
            <td>{{ p.title }}</td>
            <td>{{ p.price }} {{ p.currency }}</td>
            <td>{{ p.keywords.join(", ") || "—" }}</td>
            <td>{{ p.is_active ? "активен" : "выкл" }}</td>
            <td class="row">
              <button class="secondary" @click="toggle(p)">
                {{ p.is_active ? "Выключить" : "Включить" }}
              </button>
              <button class="danger" @click="remove(p.id)">Удалить</button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
