// services/web/apps/seller-dashboard/src/components/Layout.vue
<script setup lang="ts">
import { useAuth } from "../composables/useAuth";

const { seller, logout } = useAuth();
</script>

<template>
  <div class="layout">
    <aside class="sidebar">
      <h1>Sellbot</h1>
      <p style="opacity: 0.8; margin-bottom: 16px">{{ seller?.full_name || seller?.username }}</p>
      <nav>
        <RouterLink to="/" active-class="active">Статистика</RouterLink>
        <RouterLink to="/catalog" active-class="active">Каталог</RouterLink>
        <RouterLink to="/leads" active-class="active">Лиды</RouterLink>
        <RouterLink to="/workers" active-class="active">Воркеры</RouterLink>
      </nav>
      <button class="secondary" style="margin-top: 24px" @click="logout()">Выйти</button>
    </aside>
    <main class="content">
      <RouterView />
    </main>
  </div>
</template>

// services/seller-dashboard/src/components/Layout.tsx
import { NavLink, Outlet } from "react-router-dom";
import { useAuth } from "../auth";

export function Layout() {
  const { seller, logout } = useAuth();

  return (
    <div className="layout">
      <aside className="sidebar">
        <h1>Sellbot</h1>
        <p style={{ opacity: 0.8, marginBottom: 16 }}>{seller?.full_name || seller?.username}</p>
        <nav>
          <NavLink to="/" end>
            Статистика
          </NavLink>
          <NavLink to="/catalog">Каталог</NavLink>
          <NavLink to="/leads">Лиды</NavLink>
          <NavLink to="/workers">Воркеры</NavLink>
        </nav>
        <button className="secondary" style={{ marginTop: 24 }} onClick={() => void logout()}>
          Выйти
        </button>
      </aside>
      <main className="content">
        <Outlet />
      </main>
    </div>
  );
}
